In [2]:
import numpy as np 
performans=np.random.randint(50,100, size=(8,6))

In [3]:
çalışanlar={"ayşe":performans[:,0],"şahmaran":performans[:,1],"delican":performans[:,2],"keremişko":performans[:,3],"denizişko":performans[:,4],"enesişko":performans[:,5]}

In [4]:
performans

array([[66, 59, 58, 92, 92, 78],
       [91, 59, 89, 87, 81, 85],
       [92, 75, 60, 67, 80, 54],
       [72, 62, 86, 99, 56, 54],
       [67, 51, 68, 81, 63, 59],
       [87, 90, 85, 96, 81, 71],
       [64, 96, 83, 87, 64, 53],
       [62, 83, 79, 53, 89, 80]], dtype=int32)

In [5]:
performans.shape # matrisin kaça kaç kuruldupunu gösterir (shape)

(8, 6)

In [6]:
performans.ndim # haç boyutlu olduğunu gösterir (ndim) bir yatay bir dikey toplam iki boyut

2

In [7]:
performans.dtype # matrisin veri tipini gösterir

dtype('int32')

In [8]:
performans.sum() # matrisin toplamını gösterir 

np.int64(3586)

In [9]:
performans.max() # matrisin en büyük verisi

np.int32(99)

In [10]:
performans.argmax() # matrisdeki en büyük veri 27. indexdeymiş

np.int64(21)

In [11]:
performans[:,0] # 1. çalışanın 8 aylık performansı 

array([66, 91, 92, 72, 67, 87, 64, 62], dtype=int32)

In [12]:
performans[7:] # son ayın tüm çalışanlırının  performansı

array([[62, 83, 79, 53, 89, 80]], dtype=int32)

In [13]:
performans[0:2,0:3] # ilk üç çalışanın il 2 ayını seçtik 

array([[66, 59, 58],
       [91, 59, 89]], dtype=int32)

In [14]:
performans[4,4] # [ satır , sütun ]

np.int32(63)

In [15]:
alt_matris=performans[4:6,2:7] # alt matris oluşturduk 

In [16]:
alt_matris

array([[68, 81, 63, 59],
       [85, 96, 81, 71]], dtype=int32)

In [17]:
performans +10 # burada +10 ekledik ama dizimiz kaydedilmedi 

array([[ 76,  69,  68, 102, 102,  88],
       [101,  69,  99,  97,  91,  95],
       [102,  85,  70,  77,  90,  64],
       [ 82,  72,  96, 109,  66,  64],
       [ 77,  61,  78,  91,  73,  69],
       [ 97, 100,  95, 106,  91,  81],
       [ 74, 106,  93,  97,  74,  63],
       [ 72,  93,  89,  63,  99,  90]], dtype=int32)

In [18]:
performans

array([[66, 59, 58, 92, 92, 78],
       [91, 59, 89, 87, 81, 85],
       [92, 75, 60, 67, 80, 54],
       [72, 62, 86, 99, 56, 54],
       [67, 51, 68, 81, 63, 59],
       [87, 90, 85, 96, 81, 71],
       [64, 96, 83, 87, 64, 53],
       [62, 83, 79, 53, 89, 80]], dtype=int32)

In [19]:
performans+=10 # burada +10 ekledik  ve dizimizi güncelledik kaydettik 

In [20]:
performans

array([[ 76,  69,  68, 102, 102,  88],
       [101,  69,  99,  97,  91,  95],
       [102,  85,  70,  77,  90,  64],
       [ 82,  72,  96, 109,  66,  64],
       [ 77,  61,  78,  91,  73,  69],
       [ 97, 100,  95, 106,  91,  81],
       [ 74, 106,  93,  97,  74,  63],
       [ 72,  93,  89,  63,  99,  90]], dtype=int32)

In [21]:
normalizasyon=((performans - performans.min()) / (performans.max() - performans.min())) * 100 # 100 ile normalizasyon yaptık 

In [22]:
normalizasyon.round(2) # float gösrterim çok uzadığı için round(2) yi koydum 

array([[ 31.25,  16.67,  14.58,  85.42,  85.42,  56.25],
       [ 83.33,  16.67,  79.17,  75.  ,  62.5 ,  70.83],
       [ 85.42,  50.  ,  18.75,  33.33,  60.42,   6.25],
       [ 43.75,  22.92,  72.92, 100.  ,  10.42,   6.25],
       [ 33.33,   0.  ,  35.42,  62.5 ,  25.  ,  16.67],
       [ 75.  ,  81.25,  70.83,  93.75,  62.5 ,  41.67],
       [ 27.08,  93.75,  66.67,  75.  ,  27.08,   4.17],
       [ 22.92,  66.67,  58.33,   4.17,  79.17,  60.42]])

In [23]:
ay1=performans[:,0]
ay2=performans[:,1]
ay1>ay2 # ilk ve ikinci ayı karşılaştırdık 

array([ True,  True,  True,  True,  True, False, False, False])

In [24]:
performans.mean(axis=1).round(2) # bize  her bi ayın ortalama verisini gösterdi 

array([84.17, 92.  , 81.33, 81.5 , 74.83, 95.  , 84.5 , 84.33])

In [25]:
performans.mean(axis=0).round(2) # bize her bi çalışanını ortalama verisini gösterdi 

array([85.12, 81.88, 86.  , 92.75, 85.75, 76.75])

In [26]:
performans.mean(axis=1).max() # bize çaloşanların arasındaki  max performansını gösterdi

np.float64(95.0)

In [27]:
performans.mean(axis=0).min() # bize çalışanların içindeki en düşük performansı gösterdi

np.float64(76.75)

In [28]:
performans.mean(axis=0).max() # bize ayların  arasındaki  max performansını gösterdi

np.float64(92.75)

In [29]:
performans.mean(axis=1).min() # bize ayların arasındaki en düşük performansı gösterdi

np.float64(74.83333333333333)

In [30]:
performans.reshape(6,8) # 8,6 olan diziyi 6,8 diye değiştirdik 

array([[ 76,  69,  68, 102, 102,  88, 101,  69],
       [ 99,  97,  91,  95, 102,  85,  70,  77],
       [ 90,  64,  82,  72,  96, 109,  66,  64],
       [ 77,  61,  78,  91,  73,  69,  97, 100],
       [ 95, 106,  91,  81,  74, 106,  93,  97],
       [ 74,  63,  72,  93,  89,  63,  99,  90]], dtype=int32)

In [31]:
performans.transpose() # yatay duran verileri düz , düz olanları yatay yaptı

array([[ 76, 101, 102,  82,  77,  97,  74,  72],
       [ 69,  69,  85,  72,  61, 100, 106,  93],
       [ 68,  99,  70,  96,  78,  95,  93,  89],
       [102,  97,  77, 109,  91, 106,  97,  63],
       [102,  91,  90,  66,  73,  91,  74,  99],
       [ 88,  95,  64,  64,  69,  81,  63,  90]], dtype=int32)

In [32]:
performans.ravel() # dizini tek bi satır halimnde oluşturdu

array([ 76,  69,  68, 102, 102,  88, 101,  69,  99,  97,  91,  95, 102,
        85,  70,  77,  90,  64,  82,  72,  96, 109,  66,  64,  77,  61,
        78,  91,  73,  69,  97, 100,  95, 106,  91,  81,  74, 106,  93,
        97,  74,  63,  72,  93,  89,  63,  99,  90], dtype=int32)

In [33]:
çalışanisimler=list(çalışanlar.keys())
ay_isimleri = ["Ay1", "Ay2", "Ay3", "Ay4", "Ay5", "Ay6"]

In [35]:
eniyiçalışanindex=performans.mean(axis=1).argmax() #en iyi çalışan  
enbaşarılıçalışan=çalışanisimler[eniyiçalışanindex]

In [36]:
eniyiayindex=performans.mean(axis=0).argmax() #  en yüksek getirili ayı grtirdi
eniyiay=ay_isimleri[eniyiayindex]

In [37]:
print(f" en başarılı çalışan: {enbaşarılıçalışan}")

 en başarılı çalışan: enesişko


In [38]:
print(f" en yüksek ay ortalaması : {eniyiay}")

 en yüksek ay ortalaması : Ay4


In [39]:
print(f"genel ortalama performans : {performans.mean()} ")

genel ortalama performans : 84.70833333333333 
